title: Tuebor
description: Tuebor is a commitment to invest in at least one Michigan-based startup per year.
theme: just-the-docs

baseurl: ""
url: https://tuebor.org

logo: "https://github.com/arepb/tuebor/blob/7fbafd77aad9e75b15cfc106344660fdd3eab1f8/assets/images/%E2%80%8ETuebor%20logo%20400.png"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
