title: Tueborx
description: Tuebor is a commitment to invest in at least one Michigan-based startup per year.
theme: just-the-docs

baseurl: ""
url: https://tuebor.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
