title: Tuebor
description: Tuebor is a commitment to invest in at least one Michigan-based startup per year.
theme: just-the-docs

baseurl: ""
url: https://tuebor.org

logo: "https://raw.githubusercontent.com/arepb/tuebor/main/assets/images/%E2%80%8ETuebor-log.%E2%80%8E002.png"

favicon_ico: "/assets/images/favicon.ico"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
