title: Tuebor
description: An honor-pledge commitment by the people who really love Michigan.
baseurl: ""
url: https://tuebor.org

favicon_ico: "/assets/images/favicon.ico"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - index-test.md
  - vendor
  - _sass
  - _includes/components
  - _includes/css
  - _includes/icons
  - _includes/js
  - _includes/lunr
  - _includes/vendor

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
